name: Deploy Laravel Estufas Project

on: 
    push:
      branches: [ "main" ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with: 
          php-version: 8.2

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Composer Dependencies
        run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

      - name: Install Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '20'
      
      - name: Install NPM Dependencies
        run: npm install

      - name: Build NPM Asests
        run: npm run build

      - name: Synchronize Files To Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/home2/fel78912/public_html/laravel"

      - name: Run Remote/Artisan Commands
        uses: appleboy/ssh-action@v0.1.6
        with: 
          host: ${{ secrets.REMOTE_HOST}}
          username: ${{ secrets.REMOTE_USER}}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          script: |
           ssh -o KexAlgorithms=diffie-hellman-group14-sha256 ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "cd /home2/fel78912/public_html/laravel && php artisan migrate --force && php artisan optimize"
